### PR TITLE
Update Vietnamese diacritics and special characters

### PR DESCRIPTION
**Pull request by anhdung98**
Some characters were corrupted when I tested in Vietnamese. (Special characters in Vietnamese: đ á à ả ã ạ é è ẻ ẽ ẹ í ì ỉ ĩ ị ó ò ỏ õ ọ ú ù ủ ũ ụ ý ỳ ỷ ỹ ỵ ă ắ ằ ẳ ẵ ặ â ấ ầ ẩ ẫ ậ ê ế ề ể ễ ệ ô ố ồ ổ ỗ ộ ơ ớ ờ ở ỡ ợ ư ứ ừ ử ữ ự)

I have added 3 diacritics and some special lowercase characters in Vietnamese. Due to insufficient height of the diacritics, I did not add uppercase characters.

Please add JS minify yourself.

### CODE REVIEW

**Comment by davidkonrad** [comment]
Hey @anhdung98 , sorry for the long delay. Have just seen your PR now. I will investigate the pull request tomorrow, you seem to have done a lot of changes, but think they are OK 🙂

**Comment by davidkonrad** [comment]
merged pull request, will update docs and so on, and add you as contributor. Than you!

**Comment by davidkonrad** [comment]
@anhdung98  "Due to insufficient height of the diacritics, I did not add uppercase characters." - that is exactly why many latin chars looks awful in uppercase as well.

**Comment by anhdung98** [comment]
I forgot that I created a pull request with another email, thank you for the reminder. I have now added that email address to my GitHub account. Thank you again!

**Pull request merged**
